OrdererOrgs:
  - Name: OrderingService
    Domain: healthchain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.healthchain.com
    Template:
      Count: 2
    Users:
      Count: 2